const state={students:[],pdfDoc:null,loadingPdf:null,pdfJs:null,previewing:new Set()};
const $=id=>document.getElementById(id);
const normalize=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadData(){const r=await fetch('students.json',{cache:'force-cache'});if(!r.ok)throw Error('data');state.students=await r.json()}
function matches(s,nq){const name=normalize(s.name),cls=normalize(s.classRoll),adm=normalize(s.admissionRoll),reg=normalize(s.registrationNo);return name.includes(nq)||cls.includes(nq)||adm.includes(nq)||reg.includes(nq)||(nq.length===3&&cls.endsWith(nq))}
function render(query=''){const q=query.trim();if(!q){$('status').textContent='';$('results').innerHTML='<div class="empty">সার্চ বক্সে নাম, রোল বা Admission Roll লিখুন।</div>';return}const nq=normalize(q);const hits=state.students.filter(s=>matches(s,nq));$('status').textContent=hits.length?`${hits.length} জন পাওয়া গেছে — প্রতিটির কার্ড নিচে Preview করুন`:'কোনো matching student পাওয়া যায়নি।';if(!hits.length){$('results').innerHTML='<div class="empty">এই নামে/রোলে কোনো Registration Card পাওয়া যায়নি।</div>';return}$('results').innerHTML=hits.map((s,i)=>`<article class="result"><div class="preview-wrap"><div class="corner-mark" title="এই কার্ডটি দেখুন">✓</div><div class="preview" id="preview-${i}"><div class="preview-loading">কার্ড Preview হচ্ছে…</div></div><button class="zoom" data-index="${i}" type="button">🔍 বড় করে দেখুন</button></div><div class="identity"><div class="name">${esc(s.name)}</div><div class="meta"><span>পিতা: ${esc(s.father||'—')}</span><span>Class Roll: ${esc(s.classRoll||'—')}</span><span>Admission Roll: ${esc(s.admissionRoll)}</span><span>Registration No: ${esc(s.registrationNo)}</span></div><span class="tag ${s.inStudentList?'':'outside'}">${s.inStudentList?'Student List-এ আছে':'Student List-এর বাইরে · Card-এ আছে'} · Page ${s.page}</span><button class="download" data-index="${i}" type="button">PDF Download</button></div></article>`).join('');hits.forEach((s,i)=>renderPreview(s,i));[...$('results').querySelectorAll('.download')].forEach(b=>b.onclick=()=>downloadCard(hits[+b.dataset.index],b));[...$('results').querySelectorAll('.zoom')].forEach(b=>b.onclick=()=>openZoom(hits[+b.dataset.index]));}
async function ensurePdf(){if(state.pdfDoc)return state.pdfDoc;if(!state.loadingPdf){state.loadingPdf=(async()=>{const r=await fetch('registration-cards.pdf',{cache:'force-cache'});if(!r.ok)throw Error('pdf');const bytes=await r.arrayBuffer();state.pdfDoc=await PDFLib.PDFDocument.load(bytes);return state.pdfDoc})()}return state.loadingPdf}
async function ensurePdfJs(){if(state.pdfJs)return state.pdfJs;if(!state.pdfJs){state.pdfJs=(async()=>{if(!window.pdfjsLib){await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';sc.onload=resolve;sc.onerror=reject;document.head.appendChild(sc)});}window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const r=await fetch('registration-cards.pdf',{cache:'force-cache'});if(!r.ok)throw Error('pdf');return await window.pdfjsLib.getDocument({data:new Uint8Array(await r.arrayBuffer())}).promise})()}return state.pdfJs}
async function renderPreview(s,i,large=false){const box=$(`${large?'zoomPreview':'preview'}-${i}`);if(!box)return;try{const pdf=await ensurePdfJs();const page=await pdf.getPage(s.page);const base=page.getViewport({scale:1});const width=large?Math.min(window.innerWidth-36,900):Math.min(360,box.clientWidth||320);const scale=width/base.width;const vp=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.floor(vp.width);canvas.height=Math.floor(vp.height);canvas.className='pdf-canvas';box.innerHTML='';box.appendChild(canvas);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise}catch(e){box.innerHTML='<div class="preview-loading">Preview লোড করা যায়নি। Download বাটন ব্যবহার করুন।</div>';console.error(e)}}
function openZoom(s){const modal=$('modal');$('modalTitle').textContent=s.name;$('modalInfo').textContent=`Father: ${s.father||'—'} · Class Roll: ${s.classRoll||'—'} · Admission Roll: ${s.admissionRoll} · Registration No: ${s.registrationNo}`;$('zoomPreview').innerHTML='<div class="preview-loading">বড় Preview হচ্ছে…</div>';modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');renderPreview(s,0,true)}
function closeZoom(){$('modal').classList.remove('show');$('modal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
async function downloadCard(s,b){const old=b.textContent;b.disabled=true;b.textContent='Preparing…';try{const src=await ensurePdf(),out=await PDFLib.PDFDocument.create(),[p]=await out.copyPages(src,[s.page-1]);out.addPage(p);const bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=`registration-card-${s.admissionRoll}-${normalize(s.name).slice(0,40)}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){alert('PDF তৈরি করা যায়নি। আবার চেষ্টা করুন।');console.error(e)}finally{b.disabled=false;b.textContent=old}}
$('search').addEventListener('input',e=>render(e.target.value));$('clearBtn').onclick=()=>{$('search').value='';render();$('search').focus()};$('closeModal').onclick=closeZoom;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeZoom()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeZoom()});loadData().then(()=>render()).catch(e=>{$('status').textContent='Data load error';$('results').innerHTML='<div class="empty">ডেটা লোড করা যায়নি।</div>';console.error(e)});
